services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: reviewdibo
      POSTGRES_PASSWORD: reviewdibo
      POSTGRES_DB: reviewdibo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
